# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  description: "Moving code-gen out of `build.rs`"
  homepage: "docs.rs/codegenrs"
  topics: "rust build codegen"
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: master

  # Preference: people do clean commits
  allow_merge_commit: true
  # Backup in case we need to clean up commits
  allow_squash_merge: true
  # Not really needed
  allow_rebase_merge: false

  # Manual: allow_auto_merge: true, see https://github.com/probot/settings/issues/402
  delete_branch_on_merge: true

labels:
  # Type
  - name: bug
    color: '#b60205'
    description: "Not as expected"
  - name: enhancement
    color: '#1d76db'
    description: "Improve the expected"
  # Flavor
  - name: question
    color: "#cc317c"
    description: "Uncertainty is involved"
  - name: breaking-change
    color: "#e99695"
  - name: good first issue
    color: '#c2e0c6'
    description: "Help wanted!"

# This serves more as documentation.
# Branch protection API was replaced by rulesets but settings isn't updated.
# See https://github.com/repository-settings/app/issues/825
#
# branches:
#   - name: master
#     protection:
#       required_pull_request_reviews: null
#       required_conversation_resolution: true
#       required_status_checks:
#         # Required. Require branches to be up to date before merging.
#         strict: false
#         contexts: ["CI", "Spell Check with Typos"]
#       enforce_admins: false
#       restrictions: null
