schedules:
- cron: "3 3 3 * *"
  displayName: Monthly Build
  branches:
    include:
    - master

stages:
 - template: azure/stages.yml@templates
   parameters:
     minrust: 1.34.0
     codecov_token: $(CODECOV_TOKEN_SECRET)
 - stage: Committed
   dependsOn: check
   jobs:
   - job: "Committed"
     pool:
       vmImage: 'ubuntu-16.04'
     steps:
     - checkout: self
     - template: azure/install-rust.yml@templates
     - script: git log --graph --oneline
       displayName: Check history
     # The extra verbosity is to help verify the example we're giving works and doesn't need to be copied
     - script: cargo run -- HEAD~..HEAD^2 --no-merge-commit -vvvv
       displayName: Committed
     condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: crate-ci
